apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: ecommerce-data-platform
  labels:
    app.kubernetes.io/part-of: data-platform
type: Opaque
stringData:
  # MySQL
  mysql-root-password: "change-me"
  mysql-password: "change-me"
  # PostgreSQL
  postgres-password: "change-me"
  # MinIO
  minio-root-user: "admin"
  minio-root-password: "change-me"
  # ClickHouse
  clickhouse-password: "change-me"
  # Airflow
  airflow-fernet-key: "change-me"
  airflow-admin-user: "admin"
  airflow-admin-password: "change-me"
  # Superset
  superset-secret-key: "change-me"
  # Grafana
  grafana-admin-user: "admin"
  grafana-admin-password: "change-me"
