ecommerce:
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: clickhouse
      port: 9000
      user: default
      password: clickhouse123
      schema: ecommerce
      database: ecommerce
      threads: 4
      connect_timeout: 30
      send_receive_timeout: 300
    prod:
      type: clickhouse
      host: clickhouse
      port: 9000
      user: default
      password: clickhouse123
      schema: ecommerce
      database: ecommerce
      threads: 8
      connect_timeout: 30
      send_receive_timeout: 600
